apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-ingress-hello-world
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: echo.toall
    http:
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 8080
  - host: greetings.toall
    http:
      paths:
      - path: /munich
        backend:
          serviceName: munich
          servicePort: 80
      - path: /paris
        backend:
          serviceName: paris
          servicePort: 80
